### ISSUE TITLE
raise TypeError when transfer "嗯"

### ISSUE THREAD

**Issue by shootingfly** [wxianfeng/hanzi_to_pinyin#3]
```ruby
HanziToPinyin.hanzi_to_pinyin("嗯")
```

![image](https://user-images.githubusercontent.com/20180317/96411112-8c772400-121a-11eb-9a33-b7f620f1acec.png)

**Comment by iamwxianfeng** [comment]
ok，我处理下&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shootingfly"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 下午2:52
收件人: "wxianfeng/hanzi_to_pinyin"<hanzi_to_pinyin@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [wxianfeng/hanzi_to_pinyin] raise TypeError when transfer &quot;嗯&quot; (#3)





 HanziToPinyin.hanzi_to_pinyin("嗯")

**Comment by wxianfeng** [comment]
done

https://rubygems.org/gems/hanzi_to_pinyin/versions/2.0.1
